
LABEL_MAP = {
    'abandoned (overgrown)' : ['overgrowth', 'land', 'land'],
    'abandoned (shrubs)': ['shrub', 'land', 'land'],
    'agrume': ['citrus', 'fruit', 'fruit'],
    'alfalfa': ['alfalfa', 'herb', 'vegetable'],
    'ananas': ['pineapple', 'berry', 'fruit'],
    'aneth': ['dill', 'herb', 'vegetable'],
    'apples': ['apple', 'pome', 'fruit'],
    'apricots': ['apricot', 'drupe', 'fruit'],
    'arachide': ['peanut', 'legume', 'legume'],
    'artichaut': ['artichoke', 'flower', 'vegetable'],
    'artichoke': ['artichoke', 'flower', 'vegetable'] ,
    'asparagus': ['Asparagus', 'Herb',', ''Vegetable'],
    'aubergine': ['Eggplant', 'Nightshade', 'Vegetable'],
    'autre céréale de genre fagopyrum': ['Buckwheat', 'Grain', 'Grain'],
    'autre céréale de genre panicum': ['Switchgrass', 'Grain', 'Grain'],
    'autre céréale de printemps de genre zea': ['Spring Cereal', 'Grain', 'Grain'],
    'autre céréale d\x92hiver de genre triticum': ['Other Cereal', 'Grain', 'Grain'],
    'autre céréale d\x92un autre genre': ['Other Cereal', 'Grain', 'Grain'],
    'autre fourrage annuel d\x92un autre genre': ['Fodder', 'Fodder', 'Fodder'],
    'autre féverole fourragère': ['Bean', 'Bean', 'Legume'],
    'autre graminée fourragère pure de 5 ans ou moins': ['Forage', 'Fodder', 'Fodder'],
    'autre luzerne': ['Alfalfa', 'Herb', 'Vegetable'],
    'autre légume ou fruit annuel': ['Other Fruit', 'Fruit', 'Fruit'],
    'autre légume ou fruit pérenne': ['Other Vegetable', 'Vegetable', 'Vegetable'],
    'autre mélilot': ['Clover', 'Herb', 'Vegetable'],
    'autre oléagineux d\x92un autre genre': ['Oilseed', 'Seed', 'Seed'],
    'autre plante fourragère sarclée d\x92un autre genre': ['Fodder', 'Fodder', 'Fodder'],
    'autre plante à parfum, aromatique et médicinale annuelle': ['Medicinal', 'Other Crop', 'Other Crop'],
    'autre plante à parfum, aromatique et médicinale pérenne': ['Medicinal', 'Other Crop', 'Other Crop'],
    'autre pois fourrager de printemps': ['Pea', 'Legume', 'Legume'],
    'autre pois fourrager d\x92hiver': ['Pea', 'Legume', 'Legume'],
    'autre prairie temporaire de 5 ans ou moins': ['Grassland', 'Land/Structure', 'Land/Structure'],
    'autre sainfoin': ['Pea', 'Legume', 'Legume'],
    'autre trèfle': ['Clover', 'Herb', 'Legume'],
    'autre vesce': ['Vegetable', 'Vegetable', 'Vegetable'],
    'avocat': ['Avocado', 'Avocado', 'Vegetable'],
    'avoine de printemps': ['Spring Oats', 'Grain', 'Grain'],
    'avoine d\x92hiver': ['Winter Oats', 'Grain', 'Grain'],
    'aïl': ['Garlic', 'Root', 'Root'],
    'banana': ['Banana', 'Fruit', 'Fruit'],
    'banane créole (fruit et légume) - autre': ['Banana', 'Fruit', 'Fruit'],
    'banane créole (fruit et légume) - fermage': ['Banana', 'Fruit', 'Fruit'],
    'banane créole (fruit et légume) - indivision': ['Banana', 'Fruit', 'Fruit'],
    'banane créole (fruit et légume) - propriété ou faire valoir direct': ['Banana', 'Fruit', 'Fruit'],
    'banane créole (fruit et légume) - réforme foncière': ['Banana', 'Fruit', 'Fruit'],
    'banane export - autre': ['Banana', 'Fruit', 'Fruit'],
    'banane export - fermage': ['Banana', 'Fruit', 'Fruit'],
    'banane export - indivision': ['Banana', 'Fruit', 'Fruit'],
    'banane export - propriété ou faire valoir direct': ['Banana', 'Fruit', 'Fruit'],
    'barley': ['Barley', 'Grain', 'Grain'],
    'barley (undiff)': ['Barley', 'Grain', 'Grain'],
    'barren': ['Barren', 'Land/Structure', 'Land/Structure'],
    'basilic': ['Basil', 'Herb', 'Vegetable'],
    'bean': ['Bean', 'Legume', 'Legume'],
    'beans (undiff)': ['Bean', 'Legume', 'Legume'],
    'beetroot': ['Beet', 'Root', 'Vegetable'],
    'betterave fourragère': ['Beet', 'Root', 'Vegetable'],
    'betterave non fourragère / bette': ['Beet', 'Root', 'Vegetable'],
    'biofuel (undiff)': ['Biofuel', 'Other Crop', 'Other Crop'],
    'birdsfoot trefoil': ['Clover', 'Herb', 'Vegetable'],
    'blackberry': ['Blackberry', 'Berry', 'Fruit'],
    'blueberry (undiff)': ['Blueberry', 'Berry', 'Fruit'],
    'blueberry - high bush': ['Blueberry', 'Berry', 'Fruit'],
    'blueberry - low bush': ['Blueberry', 'Berry', 'Fruit'],
    'blé dur de printemps': ['Spring Wheat', 'Grain', 'Grain'],
    'blé dur d\x92hiver': ['Winter Wheat', 'Grain', 'Grain'],
    'blé tendre de printemps': ['Spring Wheat', 'Grain', 'Grain'],
    'blé tendre d\x92hiver': ['Winter Wheat', 'Grain', 'Grain'],
    'bois pâturé': ['Pasture Wood', 'Tree', 'Land/Structure'],
    'brachiaria': ['Brachiaria', 'Forage', 'Fodder'],
    'broadleaf': ['Broadleaf', 'Tree', 'Non-Crop Plant'],
    'broccoli': ['Broccoli', 'Flower', 'Vegetable'],
    'brussel sprout': ['Brussel Sprout', 'Leafy Green', 'Vegetable'],
    'buckwheat': ['Buckwheat', 'Grain', 'Grain'],
    'bush bean': ['Bush Bean', 'Bean', 'Legume'],
    'cabbage': ['Cabbage', 'Leafy Green', 'Vegetable'],
    'café / cacao': ['Coffee', 'Seed', 'Seed'],
    'cameline': ['Wild Flax', 'Seed', 'Seed'],
    'camomille': ['Chamomile', 'Flower', 'Other Crop'],
    'canne à sucre - autre': ['Sugar Cane', 'Grain', 'Grain'],
    'canne à sucre - fermage': ['Sugar Cane', 'Grain', 'Grain'],
    'canne à sucre - indivision': ['Sugar Cane', 'Grain', 'Grain'],
    'canne à sucre - propriété ou faire valoir direct': ['Sugar Cane', 'Grain', 'Grain'],
    'canne à sucre - réforme foncière': ['Sugar Cane', 'Grain', 'Grain'],
    'canola/rapeseed': ['Canola', 'Seed', 'Seed'],
    'carotte': ['Carrot', 'Root', 'Vegetable'],
    'carrot': ['Carrot', 'Root', 'Vegetable'],
    'cassava': ['Cassava', 'Bean', 'Legume'],
    'cauliflower': ['Cauliflower', 'Flower', 'Vegetable'],
    'cedar': ['Cedar', 'Tree', 'Non-Crop Plant'],
    'celery': ['Celery', 'Leafy Green', 'Vegetable'],
    'cereals (undiff)': ['Cereal', 'Grain', 'Grain'],
    'cerfeuil': ['Chervil', 'Herb', 'Vegetable'],
    'cerise bigarreau pour transformation': ['Cherry', 'Drupe', 'Fruit'],
    'cerrado': ['Unused', 'Unused', 'Unused'],
    'chanvre': ['Hemp', 'Seed', 'Seed'],
    'chanvre sans étiquette conforme': ['Hemp', 'Seed', 'Seed'],
    'cherries': ['Cherry', 'Drupe', 'Fruit'],
    'chicorée / endive / scarole': ['Chicory', 'Herb', 'Vegetable'],
    'chou': ['Cabbage', 'Leafy Green', 'Vegetable'],
    'christmas trees': ['Tree', 'Tree', 'Non-Crop Plant'],
    'ciboulette': ['Chive', 'Herb', 'Vegetable'],
    'clover (undiff)': ['Clover', 'Herb', 'Vegetable'],
    'coffee': ['Coffee', 'Seed', 'Seed'],
    'colza de printemps': ['Spring Rapeseed', 'Seed', 'Seed'],
    'colza d\x92hiver': ['Winter Rapeseed', 'Seed', 'Seed'],
    'concombre / cornichon': ['Cucumber', 'Vegetable', 'Vegetable'],
    'coniferous': ['Evergreen', 'Tree', 'Non-Crop Plant'],
    'conversion area': ['Unused', 'Unused', 'Unused'],
    'coriandre': ['Coriander', 'Herb', 'Vegetable'],
    'corn': ['Corn', 'Grain', 'Vegetable'],
    'cotton': ['Cotton', 'Flower', 'Other Crop'],
    'courge musquée / butternut': ['Butternut Squash', 'Marrow', 'Vegetable'],
    'courgette / citrouille': ['Zucchini', 'Marrow', 'Vegetable'],
    'cranberry': ['Cranberry', 'Berry', 'Fruit'],
    'cresson': ['Cress', 'Herb', 'Vegetable'],
    'cucumber': ['Cucumber', 'Cucumber', 'Vegetable'],
    'culture sous serre hors sol': ['Greenhouse', 'Land/Structure', 'Land/Structure'],
    'curcuma': ['Turmeric', 'Root', 'Vegetable'],
    'céleri': ['Celery', 'Leafy Green', 'Vegetable'],
    'dactyle de 5 ans ou moins': ['Orchard Grass', 'Land/Structure', 'Land/Structure'],
    'deforested': ['Deforested Land', 'Land/Structure', 'Land/Structure'],
    'dill': ['Dill', 'Herb', 'Vegetable'],
    'dry bean': ['Dry Bean', 'Bean', 'Legume'],
    'eggplant': ['Eggplant', 'Nightshade', 'Vegetable'],
    'estragon': ['Tarragon', 'Herb', 'Vegetable'],
    'eucalyptus': ['Eucalyptus', 'Tree Fruit', 'Non-Crop Plant'],
    'fababeans': ['Favabeans', 'Bean', 'Legume'],
    'fallow': ['Fallow', 'Land/Structure', 'Land/Structure'],
    'fallowland': ['Fallow', 'Land/Structure', 'Land/Structure'],
    'fenouil': ['Fennel', 'Herb', 'Vegetable'],
    'fenugrec': ['Fenugreek', 'Herb', 'Vegetable'],
    'fescue': ['Fescue', 'Grass', 'Non-Crop Plant'],
    'field peas': ['Field Peas', 'Pea', 'Legume'],
    'flaxseed': ['Flax Seed', 'Seed', 'Seed'],
    'forage crops': ['Forage', 'Fodder', 'Fodder'],
    'forest': ['Forest', 'Land/Structure', 'Land/Structure'],
    'fourrage composé de céréales et/ou de protéagineux (en proportion <\xa050%) et/ou de légumineuses fourragères (en proportion < 50%)': ['Fodder', 'Fodder', 'Fodder'],
    'fraise': ['Strawberry', 'Berry', 'Fruit'],
    'fruits (berry & annual)': ['Berry ', 'Berry', 'Fruit'],
    'fruits (trees)': ['Tree Fruit', 'Fruit', 'Fruit'],
    'fève': ['Bean', 'Bean', 'Legume'],
    'fétuque de 5 ans ou moins': ['Fescue', 'Grass', 'Land/Structure'],
    'féverole semée avant le 31/05': ['Bean', 'Legume', 'Legume'],
    'gesse': ['Lamb', 'Livestock', 'Livestock'],
    'ginseng': ['Ginseng', 'Root', 'Root'],
    'greenfeed (mixed)': ['Greenfeed', 'Fodder', 'Fodder'],
    'greenhouse': ['Greenhouse', 'Land/Structure', 'Land/Structure'],
    'groundnut': ['Peanut', 'Legume', 'Legume'],
    'groundnuts': ['Peanut', 'Legume', 'Legume'],
    'groundnuts or peanuts': ['Peanut', 'Legume', 'Legume'],
    'géranium': ['Geranium', 'Flower', 'Non-Crop PlantBean', 'Legume', 'Legume'],
    'haricot / flageolet': ['Bean', 'Legume', 'Legume'],
    'hascap': ['Unused', 'Unused', 'Unused'],
    'hay': ['Hay', 'Fodder', 'Fodder'],
    'hazelnut': ['Hazelnut', 'Nut', 'Seed'],
    'hemp': ['Hemp', 'Seed', 'Seed'],
    'herbs': ['Herb', 'Herb', 'Vegetable'],
    'hops': ['Hops', 'Flower', 'Other Crop'],
    'horticulture ornementale de plein champ': ['Other Crop', 'Other Crop', 'Other Crop'],
    'horticulture ornementale sous abri': ['Covered Farm', 'Land/Structure', 'Land/Structure'],
    'houblon': ['Hops', 'Flower', 'Other Crop'],
    'jachère de 5 ans ou moins': ['Fallow', 'Land/Structure', 'Land/Structure'],
    'jachère de 6 ans ou plus': ['Fallow', 'Land/Structure', 'Land/Structure'],
    'jachère de 6 ans ou plus déclarée comme surface d\x92intérêt écologique': ['Fallow', 'Land/Structure', 'Land/Structure'],
    'jachère noire': ['Fallow', 'Land/Structure', 'Land/Structure'],
    'laitue / batavia / feuille de chêne': ['Lettuce', 'Leafy Green', 'Vegetable'],
    'lavande / lavandin': ['Lavender', 'Flower', 'Non-Crop Plant'],
    'lavendar': ['Lavender', 'Flower', 'Non-Crop Plant'],
    'lentille cultivée (non fourragère)': ['Lentil', 'Legume', 'Legume'],
    'lentille fourragère': ['Lentil', 'Legume', 'Legume'],
    'lentils': ['Lentil', 'Legume', 'Legume'],
    'lettuce': ['Lettuce', 'Leafy Green', 'Vegetable'],
    'lin fibres': ['Flax', 'Seed', 'Seed'],
    'lin non textile de printemps': ['Spring Flax', 'Seed', 'Seed'],
    'lin non textile d\x92hiver': ['Winter Flax', 'Seed', 'Seed'],
    'lotier': ['Clover', 'Herb', 'Vegetable'],
    'lupin doux de printemps semé avant le 31/05': ['Lupine', 'Flower', 'Non-Crop Plant'],
    'luzerne déshydratée': ['Alfalfa', 'Herb', 'Vegetable'],
    'légume sous abri': ['Covered Farm', 'Land/Structure', 'Land/Structure'],
    'maize': ['Corn', 'Grain', 'Grain'],
    'marjolaine / origan': ['Oregano', 'Herb', 'Vegetable'],
    'maïs': ['Corn', 'Grain', 'Grain'],
    'maïs doux': ['Corn', 'Grain', 'Grain'],
    'maïs ensilage': ['Corn', 'Grain', 'Grain'],
    'meadows': ['Meadows', 'Land/Structure', 'Land/Structure'],
    'melon': ['Melon', 'Fruit', 'Fruit'],
    'menthe': ['Mint', 'Herb', 'Vegetable'],
    'millet': ['Millet', 'Grain', 'Grain'],
    'miscanthus': ['Miscanthus', 'Grass', 'Non-Crop Plant'],
    'mixed forage': ['Forage', 'Fodder', 'Fodder'],
    'mixedwood': ['Tree', 'Tree', 'Non-Crop Plant'],
    'moha': ['Tree', 'Tree', 'Non-Crop Plant'],
    'moutarde': ['Mustard', 'Seed', 'Seed'],
    'mustard': ['Mustard', 'Seed', 'Seed'],
    'mâche': ['Unused', 'Unused', 'Unused'],
    'mélange de céréales': ['Cereal', 'Grain', 'Grain'],
    'mélange de légumineuses fourragères (entre elles)': ['Beans', 'Legume', 'Legume'],
    'mélange de légumineuses fourragères prépondérantes et de céréales et/ou d\x92oléagineux': ['Fodder', 'Fodder', 'Fodder'],
    'mélange de légumineuses prépondérantes au semis et de graminées fourragères de 5 ans ou moins': ['Beans', 'Legume', 'Legume'],
    'mélange de protéagineux (pois et/ou lupin et/ou féverole)': ['Beans', 'Legume', 'Legume'],
    'mélange de protéagineux (pois et/ou lupin et/ou féverole) prépondérants semés avant le 31/05 et de céréales': ['Beans', 'Legume', 'Legume'],
    'mélange d\x92oléagineux': ['Oilseed', 'Seed', 'Seed'],
    'nan': ['Unused', 'Land/Structure', 'Land/Structure'],
    'native grassland': ['Grassland', 'Land/Structure', 'Land/Structure'],
    'navet': ['Turnip', 'Root', 'Vegetable'],
    'navette d\x92été': ['Unused', 'Unused', 'Unused'],
    'noisette': ['Hazelnut', 'Nut', 'Seed'],
    'noix': ['Nuts', 'Nut', 'Seed'],
    'nursery': ['Nursery', 'Land/Structure', 'Land/Structure'],
    'nuts': ['Nuts', 'Nut', 'Seed'],
    'oats': ['Oats', 'Grain', 'Grain'],
    'oignon / échalote': ['Onion', 'Root', 'Vegetable'],
    'oil seeds': ['Oilseed', 'Seed', 'Seed'],
    'oilseeds (undiff)': ['Oilseed', 'Seed', 'Seed'],
    'onions': ['Onion', 'Root', 'Vegetable'],
    'orchard': ['Orchard', 'Land/Structure', 'Land/Structure'],
    'orge d\'hiver': ['Winter barley', 'Grain', 'Grain'],
    'orge de printemps': ['spring barley', 'Grain', 'Grain'],
    'ornemental': ['Ornamental', 'Other Crop', 'Other Crop'],
    'oseille': ['Sorrel', 'Herb', 'Vegetable'],
    'other': ['Other', 'Other Crop', 'Other Crop'],
    'other agriculture (undiff)': ['Other', 'Other Crop', 'Other Crop'],
    'other berries': ['Berries', 'Berry', 'Fruit'],
    'other forage': ['Forage', 'Fodder', 'Fodder'],
    'other nursery': ['Nursery', 'Land/Structure', 'Land/Structure'],
    'other nut': ['Nuts', 'Nut', 'Seed'],
    'other orchards': ['Orchard', 'Land/Structure', 'Land/Structure'],
    'palm': ['Palm', 'Seed', 'Seed'],
    'panais': ['Parsnip', 'Root', 'Vegetable'],
    'pasture': ['Pasture', 'Land/Structure', 'Land/Structure'],
    'pasture (undiff)': ['Pasture', 'Land/Structure', 'Land/Structure'],
    'pasture/forage': ['Pasture', 'Land/Structure', 'Land/Structure'],
    'pastèque': ['Watermelon', 'Melon', 'Fruit'],
    'peaches': ['Peach', 'Drupe', 'Fruit'],
    'pears': ['Pear', 'Pome', 'Fruit'],
    'peas (undiff)': ['Peas', 'Bean', 'Legume'],
    'peatland - harvested': ['Wetland', 'Land/Structure', 'Land/Structure'],
    'pepper': ['Pepper', 'Nightshade', 'Vegetable'],
    'persil': ['Parsley', 'Herb', 'Vegetable'],
    'petit fruit rouge': ['Red Fruit', 'Fruit', 'Fruit'],
    'petits pois': ['Peas', 'Pea', 'Legume'],
    'plantain psyllium': ['Plantain', 'Banana', 'Fruit'],
    'plante aromatique (autre que vanille)': ['Aromatic', 'Other Crop', 'Other Crop'],
    'plante médicinale': ['Medicinal', 'Other Crop', 'Other Crop'],
    'plante à parfum (autre que géranium et vétiver)': ['Perfume', 'Other Crop', 'Other Crop'],
    'plums': ['Plum', 'Drupe', 'Fruit'],
    'poireau': ['Leek', 'Leafy Green', 'Vegetable'],
    'pois chiche': ['Chickpeas', 'Pea', 'Legume'],
    'pois de printemps semé avant le 31/05': ['Spring peas', 'Pea', 'Legume'],
    'pois d\x92hiver': ['Winter peas', 'Pea', 'Legume'],
    'poivron / piment': ['Pepper', 'Nightshade', 'Vegetable'],
    'pomme de terre de consommation': ['Potato', 'Root', 'Vegetable'],
    'pomme de terre féculière': ['Potato', 'Root', 'Vegetable'],
    'poplar': ['Poplar', 'Tree', 'Land/Structure'],
    'potatoes': ['Potato', 'Root', 'Vegetable'],
    'potiron / potimarron': ['Pumpkin', 'Marrow', 'Vegetable'],
    'prairie en rotation longue (6 ans ou plus)': ['Grassland', 'Land/Structure', 'Land/Structure'],
    'prairie permanente - herbe prédominante (ressources fourragères ligneuses absentes ou peu présentes)': ['Grassland', 'Land/Structure', 'Land/Structure'],
    'prune d\x92ente pour transformation': ['Plum', 'Drupe', 'Fruit'],
    'pulses': ['Pulses', 'Legume', 'Legume'],
    'pulses (undiff)': ['Pulses', 'Legume', 'Legume'],
    'pumpkin/squash': ['Pumpkin', 'Marrow', 'Vegetable'],
    'quinoa': ['Quinoa', 'Grain', 'Grain'],
    'raddish': ['Raddish', 'Root', 'Vegetable'],
    'radis': ['Raddish', 'Root', 'Vegetable'],
    'raspberry': ['Raspberry', 'Berry', 'Fruit'],
    'ray-grass de 5 ans ou moins': ['Rye', 'Grain', 'Grain'],
    'red clover': ['Clover', 'Herb', 'Vegetable'],
    'rice': ['Rice', 'Grain', 'Grain'],
    'root crops': ['Root Crops', 'Root', 'Vegetable'],
    'rye': ['Rye', 'Grain', 'Grain'],
    'rye (undiff)': ['Rye', 'Grain', 'Grain'],
    'ryegrass': ['Rye', 'Grain', 'Grain'],
    'safflower': ['Safflower', 'Herb', 'Vegetable'],
    'sarrasin': ['Buckwheat', 'Grain', 'Grain'],
    'sarriette': ['Savory', 'Herb', 'Vegetable'],
    'sauge': ['Sage', 'Herb', 'Vegetable'],
    'seigle de printemps': ['Spring rye', 'Grain', 'Grain'],
    'seigle d\x92hiver': ['Winter rye', 'Grain', 'Grain'],
    'sesame': ['Sesame', 'Herb', 'Vegetable'],
    'shrubland': ['Shrub', 'Land/Structure', 'Land/Structure'],
    'sod': ['Fodder', 'Fodder', 'Fodder'],
    'soja': ['Soybean', 'Pea', 'Legume'],
    'sorgho': ['Sorghum', 'Grain', 'Grain'],
    'sorghum': ['Sorghum', 'Grain', 'Grain'],
    'soybean': ['Soybean', 'Pea', 'Legume'],
    'soybeans': ['Soybean', 'Pea', 'Legume'],
    'spelt': ['Spelt', 'Grain', 'Grain'],
    'spring barley': ['Spring barley', 'Grain', 'Grain'],
    'spring rye': ['Spring rye', 'Grain', 'Grain'],
    'spring triticale': ['Spring triticale', 'Grain', 'Grain'],
    'spring wheat': ['Spring wheat', 'Grain', 'Grain'],
    'strawberry': ['Strawberry', 'Berry', 'Fruit'],
    'sugarbeets': ['Sugarbeet', 'Root', 'Vegetable'],
    'sugarcane': ['Sugar cane', 'Grain', 'Grain'],
    'sunflower': ['Sunflower', 'Seed', 'Seed'],
    'sunflowers': ['Sunflower', 'Seed', 'Seed'],
    'surface pastorale - herbe prédominante et ressources fourragères ligneuses présentes': ['Fodder', 'Fodder', 'Fodder'],
    'surface pastorale - ressources fourragères ligneuses prédominantes': ['Fodder', 'Fodder', 'Fodder'],
    'sweet clover': ['Clover', 'Herb', 'Vegetable'],
    'sweet corn': ['Corn', 'Grain', 'Grain'],
    'sweetpotato': ['Sweet potato', 'Root', 'Vegetable'],
    'thym': ['Thyme', 'Herb', 'Vegetable'],
    'timothy': ['Herd\'s-grass', 'Fodder', 'Fodder'],
    'tobacco': ['Tobacco', 'Other Crop', 'Other Crop'],
    'tomate': ['Tomato', 'Nightshade', 'Vegetable'],
    'tomato': ['Tomato', 'Nightshade', 'Vegetable'],
    'tomatoes': ['Tomato', 'Nightshade', 'Vegetable'],
    'too wet to seed': ['Unused', 'Unused', 'Unused'],
    'topinambour': ['Artichoke', 'Flower', 'Vegetable'],
    'tournesol': ['Sunflower', 'Seed', 'Seed'],
    'triticale (undiff)': ['Triticale', 'Grain', 'Grain'],
    'triticale de printemps': ['Spring triticale', 'Grain', 'Grain'],
    'triticale d\x92hiver': ['Winter triticale', 'Grain', 'Grain'],
    'trèfle déshydraté': ['Clover', 'Herb', 'Vegetable'],
    'uncultivated soil': ['Soil', 'Land/Structure', 'Land/Structure'],
    'unimproved pasture': ['Pasture', 'Land/Structure', 'Land/Structure'],
    'urban': ['Urban', 'Land/Structure', 'Land/Structure'],
    'vanille': ['Vanilla', 'Herb', 'Vegetable'],
    'vanille sous bois': ['Vanilla', 'Herb', 'Vegetable'],
    'vanille verte': ['Vanilla', 'Herb', 'Vegetable'],
    'vegetables (undiff)': ['Vegetable', 'Vegetable', 'Vegetable'],
    'verger': ['Orchard', 'Land/Structure', 'Land/Structure'],
    'verger (dom)': ['Orchard', 'Land/Structure', 'Land/Structure'],
    'vesce déshydratée': ['Vegetable', 'Vegetable', 'Vegetable'],
    'vetch': ['Vegetable', 'Vegetable', 'Vegetable'],
    'vigne : raisins de cuve': ['Grapes', 'Berry', 'Fruit'],
    'vigne : raisins de cuve non en production': ['Grapes', 'Berry', 'Fruit'],
    'vigne : raisins de table': ['Grapes', 'Berry', 'Fruit'],
    'vineyard': ['Grapes', 'Berry', 'Fruit'],
    'walnut': ['Walnut', 'Nut', 'Seed'],
    'water': ['Water', 'Land/Structure', 'Land/Structure'],
    'wetland': ['Wetland', 'Land/Structure', 'Land/Structure'],
    'wheat': ['Wheat', 'Grain', 'Grain'],
    'wheat (undiff)': ['Wheat', 'Grain', 'Grain'],
    'wheatgrass': ['Wheat', 'Grain', 'Grain'],
    'white clover': ['Clover', 'Herb', 'Vegetable'],
    'white sorghum': ['White sorghum', 'Grain', 'Grain'],
    'winter barley': ['Winter barley', 'Grain', 'Grain'],
    'winter cereals': ['Winter cereals', 'Grain', 'Grain'],
    'winter rye': ['Winter rye', 'Grain', 'Grain'],
    'winter triticale': ['Winter triticale', 'Grain', 'Grain'],
    'winter wheat': ['Winter wheat', 'Grain', 'Grain'],
    'yellow maize': ['Corn', 'Grain', 'Grain'],
    'ylang-ylang': ['Ylang-ylang', 'Flower', 'Other Crop'],
    'zucchini': ['Zucchini', 'Marrow', 'Vegetable'],
    '\x8cillette': ['Unused', 'Unused', 'Unused'],
    'épeautre': ['Spelt', 'Grain', 'Grain'],
    'épinard': ['Spinach', 'Leafy Green', 'Vegetable'],
}